name: Deploy Hugo Site to  GitHub Pages

on:
  push:
    branches:
      - chapter-02-01
      - chapter-02-02
      - chapter-02-03
      - chapter-02-04

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [chapter-02-01, chapter-02-02, chapter-02-03, chapter-02-04]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Build with Hugo
        run: hugo --minify --baseURL "https://beautifulnature.github.io/hugoinaction/${{ matrix.branch }}"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-${{ github.run_id }}-${{ matrix.branch }}  # Unique naming per branch and run
          path: ./public

  deploy:
    runs-on: ubuntu-latest  
    needs: build
    
    steps:
      - name: Download artifact for deployment
        uses: actions/download-artifact@v4 
        with:
          name: github-pages-${{ github.run_id }}-${{ matrix.branch }}  # Match the unique artifact name

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
