name: GitHub Pages

on:
  push:
    branches:
    - chapter-02-04

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    
    - name: setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.112.5"

    - name: Build
      run: hugo --minify --baseURL=https://beautifulnature.github.io/hugoinaction

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        external_repository: beautifulnature/beautifulnature.github.io/hugoinaction
        publish_dir: ./public
        user_name: beautifulnature
        user_email: heimarunag@gmail.com
        publish_branch: gh_pages