name: GitHub Pages

on:
  push:
    branches:
    - chapter-02-04

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Specific Version of Hugo
      run: |
        HUGO_VERSION="0.112.5" # Specify your desired version here
        wget https://github.com/goharbor/hugo/releases/download/v$HUGO_VERSION/hugo_${HUGO_VERSION}_Linux-64bit.deb
        sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

    - name: Build
      run: hugo --minify --baseURL=https://beautifulnature.github.io/hugoinaction

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public